# KerberosSDR Python GUI

# Copyright (C) 2018-2019  Carl Laufer, Tamás Pető
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_hydra_dev.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets, QtGui

try:
    _fromUtf8 = str.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("KerberosSDR"))
        MainWindow.resize(1366, 870)
        self.centralwidget = QtWidgets.QMainWindow()
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.stackedWidget_config = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_config.setMaximumSize(QtCore.QSize(290, 16777215))
        self.stackedWidget_config.setObjectName(_fromUtf8("stackedWidget_config"))
        self.page_4 = QtWidgets.QMainWindow()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.doubleSpinBox_center_freq = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_center_freq.setDecimals(4)
        self.doubleSpinBox_center_freq.setMinimum(25.0)
        self.doubleSpinBox_center_freq.setMaximum(2000.0)
        self.doubleSpinBox_center_freq.setProperty("value", 100.0)
        self.doubleSpinBox_center_freq.setObjectName(_fromUtf8("doubleSpinBox_center_freq"))
        self.gridLayout_16.addWidget(self.doubleSpinBox_center_freq, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_16.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_16.addWidget(self.label_3, 0, 0, 1, 1)
        # Sampling Freq
        #self.doubleSpinBox_sampling_freq = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        #self.doubleSpinBox_sampling_freq.setMinimum(1.0)
        #self.doubleSpinBox_sampling_freq.setMaximum(3.2)
        #self.doubleSpinBox_sampling_freq.setObjectName(_fromUtf8("doubleSpinBox_sampling_freq"))
        #self.gridLayout_16.addWidget(self.doubleSpinBox_sampling_freq, 1, 1, 1, 1)

        self.comboBox_sampling_freq = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_sampling_freq.setObjectName(_fromUtf8("comboBox_sampling_freq"))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_sampling_freq, 1, 1, 1, 1)


        self.checkBox_en_uniform_gain = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_en_uniform_gain.setObjectName(_fromUtf8("checkBox_en_uniform_gain"))
        self.gridLayout_16.addWidget(self.checkBox_en_uniform_gain, 2, 0, 1, 1)

        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_16.addWidget(self.label_18, 3, 0, 1, 1)


        self.label_gain_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_gain_2.setObjectName(_fromUtf8("label_gain_2"))
        self.gridLayout_16.addWidget(self.label_gain_2, 4, 0, 1, 1)


        self.label_gain_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_gain_3.setObjectName(_fromUtf8("label_gain_3"))
        self.gridLayout_16.addWidget(self.label_gain_3, 5, 0, 1, 1)


        self.label_gain_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_gain_4.setObjectName(_fromUtf8("label_gain_4"))
        self.gridLayout_16.addWidget(self.label_gain_4, 6, 0, 1, 1)



        self.comboBox_gain = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_gain.setObjectName(_fromUtf8("comboBox_gain"))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_gain, 3, 1, 1, 1)




        self.comboBox_gain_2 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_gain_2.setObjectName(_fromUtf8("comboBox_gain_2"))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_gain_2, 4, 1, 1, 1)



        self.comboBox_gain_3 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_gain_3.setObjectName(_fromUtf8("comboBox_gain_3"))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_gain_3, 5, 1, 1, 1)



        self.comboBox_gain_4 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_gain_4.setObjectName(_fromUtf8("comboBox_gain_4"))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.comboBox_gain_4.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_gain_4, 6, 1, 1, 1)





        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.pushButton_set_receiver_config = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_set_receiver_config.setObjectName(_fromUtf8("pushButton_set_receiver_config"))
        self.gridLayout_17.addWidget(self.pushButton_set_receiver_config, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_8)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.checkBox_en_dc_compensation = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_en_dc_compensation.setText(_fromUtf8(""))
        self.checkBox_en_dc_compensation.setObjectName(_fromUtf8("checkBox_en_dc_compensation"))
        self.gridLayout_2.addWidget(self.checkBox_en_dc_compensation, 0, 1, 1, 1)
        self.doubleSpinBox_filterbw = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_filterbw.setMaximum(3400.0)
        self.doubleSpinBox_filterbw.setProperty("value", 150.0)
        self.doubleSpinBox_filterbw.setObjectName(_fromUtf8("doubleSpinBox_filterbw"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_filterbw, 1, 1, 1, 1)
        self.spinBox_fir_tap_size = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_fir_tap_size.setMaximum(10000)
        self.spinBox_fir_tap_size.setObjectName(_fromUtf8("spinBox_fir_tap_size"))
        self.gridLayout_2.addWidget(self.spinBox_fir_tap_size, 2, 1, 1, 1)
        self.spinBox_decimation = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_decimation.setMinimum(1)
        self.spinBox_decimation.setMaximum(1000)
        self.spinBox_decimation.setObjectName(_fromUtf8("spinBox_decimation"))
        self.gridLayout_2.addWidget(self.spinBox_decimation, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_8)
        self.checkBox_en_spectrum = QtWidgets.QCheckBox(self.page_4)
        self.checkBox_en_spectrum.setObjectName(_fromUtf8("checkBox_en_spectrum"))
        self.verticalLayout_7.addWidget(self.checkBox_en_spectrum)
        self.stackedWidget_config.addWidget(self.page_4)
        self.page = QtWidgets.QMainWindow()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_2.setContentsMargins(0,0,0,0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))

        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 1)



        self.checkBox_en_sync_display = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_en_sync_display.setText(_fromUtf8(""))
        self.checkBox_en_sync_display.setObjectName(_fromUtf8("checkBox_en_sync_display"))
        self.gridLayout_8.addWidget(self.checkBox_en_sync_display, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_8.addWidget(self.label_32, 1, 0, 1, 1)
        self.checkBox_en_noise_source = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_en_noise_source.setText(_fromUtf8(""))
        self.checkBox_en_noise_source.setObjectName(_fromUtf8("checkBox_en_noise_source"))
        self.gridLayout_8.addWidget(self.checkBox_en_noise_source, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.pushButton_del_sync_history = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_del_sync_history.setObjectName(_fromUtf8("pushButton_del_sync_history"))
        self.verticalLayout_2.addWidget(self.pushButton_del_sync_history)
        self.pushButton_sync = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_sync.setObjectName(_fromUtf8("pushButton_sync"))
        self.verticalLayout_2.addWidget(self.pushButton_sync)
        self.pushButton_iq_calib = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_iq_calib.setObjectName(_fromUtf8("pushButton_iq_calib"))
        self.verticalLayout_2.addWidget(self.pushButton_iq_calib)

        # Add Resync Time Control Box
        self.label_resync_time = QtWidgets.QLabel(self.groupBox)
        self.label_resync_time.setObjectName(_fromUtf8("label_resync_time"))
        self.gridLayout_8.addWidget(self.label_resync_time, 2, 0, 1, 1)

        self.spinBox_resync_time = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_resync_time.setObjectName(_fromUtf8("spinBox_resync_time"))
        self.spinBox_resync_time.setMinimum(0)
        self.spinBox_resync_time.setMaximum(99999)

        self.gridLayout_8.addWidget(self.spinBox_resync_time, 2, 1, 1, 1)




        self.gridLayout_9.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.stackedWidget_config.addWidget(self.page)
        self.page_2 = QtWidgets.QMainWindow()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.comboBox_antenna_alignment = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_antenna_alignment.setObjectName(_fromUtf8("comboBox_antenna_alignment"))
        self.comboBox_antenna_alignment.addItem(_fromUtf8(""))
        self.comboBox_antenna_alignment.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_antenna_alignment, 0, 1, 1, 1)
        self.doubleSpinBox_DOA_d = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_DOA_d.setDecimals(4)
        #self.doubleSpinBox_DOA_d.setMaximum(10.0)
        self.doubleSpinBox_DOA_d.setProperty("value", 0.5)
        self.doubleSpinBox_DOA_d.setObjectName(_fromUtf8("doubleSpinBox_DOA_d"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_DOA_d, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.pushButton_DOA_cal_90 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_DOA_cal_90.setObjectName(_fromUtf8("pushButton_DOA_cal_90"))
        self.gridLayout_7.addWidget(self.pushButton_DOA_cal_90, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_en_DOA_MEM = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_MEM.setText(_fromUtf8(""))
        self.checkBox_en_DOA_MEM.setObjectName(_fromUtf8("checkBox_en_DOA_MEM"))
        self.gridLayout.addWidget(self.checkBox_en_DOA_MEM, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.checkBox_en_DOA_Bartlett = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_Bartlett.setText(_fromUtf8(""))
        self.checkBox_en_DOA_Bartlett.setObjectName(_fromUtf8("checkBox_en_DOA_Bartlett"))
        self.gridLayout.addWidget(self.checkBox_en_DOA_Bartlett, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.checkBox_en_DOA_Capon = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_Capon.setText(_fromUtf8(""))
        self.checkBox_en_DOA_Capon.setObjectName(_fromUtf8("checkBox_en_DOA_Capon"))
        self.gridLayout.addWidget(self.checkBox_en_DOA_Capon, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.spinBox_DOA_sample_size = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_DOA_sample_size.setMinimum(1)
        self.spinBox_DOA_sample_size.setMaximum(22)
        self.spinBox_DOA_sample_size.setProperty("value", 15)
        self.spinBox_DOA_sample_size.setObjectName(_fromUtf8("spinBox_DOA_sample_size"))
        self.gridLayout.addWidget(self.spinBox_DOA_sample_size, 7, 1, 1, 1)
        self.checkBox_en_DOA_MUSIC = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_MUSIC.setText(_fromUtf8(""))
        self.checkBox_en_DOA_MUSIC.setObjectName(_fromUtf8("checkBox_en_DOA_MUSIC"))
        self.gridLayout.addWidget(self.checkBox_en_DOA_MUSIC, 5, 1, 1, 1)
        self.checkBox_en_DOA = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA.setText(_fromUtf8(""))
        self.checkBox_en_DOA.setChecked(True)
        self.checkBox_en_DOA.setObjectName(_fromUtf8("checkBox_en_DOA"))
        self.gridLayout.addWidget(self.checkBox_en_DOA, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 8, 0, 1, 1)
        self.checkBox_en_DOA_FB_avg = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_FB_avg.setText(_fromUtf8(""))
        self.checkBox_en_DOA_FB_avg.setObjectName(_fromUtf8("checkBox_en_DOA_FB_avg"))
        self.gridLayout.addWidget(self.checkBox_en_DOA_FB_avg, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        font = QtWidgets.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.stackedWidget_config.addWidget(self.page_2)
        self.page_3 = QtWidgets.QMainWindow()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_en_passive_radar = QtWidgets.QCheckBox(self.page_3)
        self.checkBox_en_passive_radar.setObjectName(_fromUtf8("checkBox_en_passive_radar"))
        self.verticalLayout_3.addWidget(self.checkBox_en_passive_radar)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_11.addWidget(self.label_14, 1, 0, 1, 1)
        self.spinBox_surv_ch_select = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_surv_ch_select.setMaximum(3)
        self.spinBox_surv_ch_select.setProperty("value", 1)
        self.spinBox_surv_ch_select.setObjectName(_fromUtf8("spinBox_surv_ch_select"))
        self.gridLayout_11.addWidget(self.spinBox_surv_ch_select, 1, 1, 1, 1)
        self.spinBox_ref_ch_select = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_ref_ch_select.setMaximum(3)
        self.spinBox_ref_ch_select.setObjectName(_fromUtf8("spinBox_ref_ch_select"))
        self.gridLayout_11.addWidget(self.spinBox_ref_ch_select, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_11.addWidget(self.label_30, 2, 0, 1, 1)
        self.spinBox_pr_sample_size = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_pr_sample_size.setMaximum(25)
        self.spinBox_pr_sample_size.setProperty("value", 15)
        self.spinBox_pr_sample_size.setObjectName(_fromUtf8("spinBox_pr_sample_size"))
        self.gridLayout_11.addWidget(self.spinBox_pr_sample_size, 2, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_18.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_18.addWidget(self.label_25, 1, 0, 1, 1)
        self.checkBox_en_td_filter = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_en_td_filter.setText(_fromUtf8(""))
        self.checkBox_en_td_filter.setObjectName(_fromUtf8("checkBox_en_td_filter"))
        self.gridLayout_18.addWidget(self.checkBox_en_td_filter, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_18.addWidget(self.label_26, 2, 0, 1, 1)
        self.spinBox_td_filter_dimension = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_td_filter_dimension.setMinimum(1)
        self.spinBox_td_filter_dimension.setMaximum(16384)
        self.spinBox_td_filter_dimension.setProperty("value", 127)
        self.spinBox_td_filter_dimension.setObjectName(_fromUtf8("spinBox_td_filter_dimension"))
        self.gridLayout_18.addWidget(self.spinBox_td_filter_dimension, 2, 1, 1, 1)
        self.comboBox_td_filter_method = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_td_filter_method.setObjectName(_fromUtf8("comboBox_td_filter_method"))
        self.comboBox_td_filter_method.addItem(_fromUtf8(""))
        self.gridLayout_18.addWidget(self.comboBox_td_filter_method, 1, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)

        #self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_9 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.doubleSpinBox_cc_det_max_Doppler = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.doubleSpinBox_cc_det_max_Doppler.setMaximum(100000.0)
        self.doubleSpinBox_cc_det_max_Doppler.setProperty("value", 500.0)
        self.doubleSpinBox_cc_det_max_Doppler.setObjectName(_fromUtf8("doubleSpinBox_cc_det_max_Doppler"))
        self.gridLayout_20.addWidget(self.doubleSpinBox_cc_det_max_Doppler, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_20.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_20.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_9)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_20.addWidget(self.label_29, 2, 0, 1, 1)
        self.doubleSpinBox_cc_det_max_range = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.doubleSpinBox_cc_det_max_range.setMaximum(100000.0)
        self.doubleSpinBox_cc_det_max_range.setProperty("value", 128.0)
        self.doubleSpinBox_cc_det_max_range.setObjectName(_fromUtf8("doubleSpinBox_cc_det_max_range"))
        self.gridLayout_20.addWidget(self.doubleSpinBox_cc_det_max_range, 0, 1, 1, 1)
        self.comboBox_cc_det_windowing = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_cc_det_windowing.setObjectName(_fromUtf8("comboBox_cc_det_windowing"))
        self.comboBox_cc_det_windowing.addItem(_fromUtf8(""))
        self.comboBox_cc_det_windowing.addItem(_fromUtf8(""))
        self.gridLayout_20.addWidget(self.comboBox_cc_det_windowing, 2, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_9)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_20.addWidget(self.label_31, 3, 0, 1, 1)
        self.spinBox_rd_dyn_range = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinBox_rd_dyn_range.setMaximum(100)
        self.spinBox_rd_dyn_range.setProperty("value", 20)
        self.spinBox_rd_dyn_range.setObjectName(_fromUtf8("spinBox_rd_dyn_range"))
        self.gridLayout_20.addWidget(self.spinBox_rd_dyn_range, 3, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.verticalLayout_3.addWidget(self.groupBox_9)


        self.groupBox_10 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.label_35 = QtWidgets.QLabel(self.groupBox_10)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_22.addWidget(self.label_35, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_10)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_22.addWidget(self.label_34, 3, 0, 1, 1)
        self.checkBox_en_autodet = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_en_autodet.setText(_fromUtf8(""))
        self.checkBox_en_autodet.setObjectName(_fromUtf8("checkBox_en_autodet"))
        self.gridLayout_22.addWidget(self.checkBox_en_autodet, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_10)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_22.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_10)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_22.addWidget(self.label_36, 2, 0, 1, 1)
        self.spinBox_cfar_est_win = QtWidgets.QSpinBox(self.groupBox_10)
        self.spinBox_cfar_est_win.setMaximum(100)
        self.spinBox_cfar_est_win.setProperty("value", 10)
        self.spinBox_cfar_est_win.setObjectName(_fromUtf8("spinBox_cfar_est_win"))
        self.gridLayout_22.addWidget(self.spinBox_cfar_est_win, 1, 1, 1, 1)
        self.spinBox_cfar_guard_win = QtWidgets.QSpinBox(self.groupBox_10)
        self.spinBox_cfar_guard_win.setProperty("value", 4)
        self.spinBox_cfar_guard_win.setObjectName(_fromUtf8("spinBox_cfar_guard_win"))
        self.gridLayout_22.addWidget(self.spinBox_cfar_guard_win, 2, 1, 1, 1)
        self.doubleSpinBox_cfar_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_cfar_threshold.setProperty("value", 13.0)
        self.doubleSpinBox_cfar_threshold.setObjectName(_fromUtf8("doubleSpinBox_cfar_threshold"))
        self.gridLayout_22.addWidget(self.doubleSpinBox_cfar_threshold, 3, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_10)


        # Peak hold groupbox
        self.groupBox_11 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.label_37 = QtWidgets.QLabel(self.groupBox_11)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_25.addWidget(self.label_37, 0, 0, 1, 1)
        self.checkBox_en_peakhold = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_en_peakhold.setText(_fromUtf8(""))
        self.checkBox_en_peakhold.setObjectName(_fromUtf8("checkBox_en_peakhold"))
        self.gridLayout_25.addWidget(self.checkBox_en_peakhold, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_11)



        self.stackedWidget_config.addWidget(self.page_3)
        self.verticalLayout_6.addWidget(self.stackedWidget_config)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_power_level = QtWidgets.QLabel(self.groupBox_6)
        self.label_power_level.setObjectName(_fromUtf8("label_power_level"))
        self.gridLayout_14.addWidget(self.label_power_level, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_14.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_update_rate = QtWidgets.QLabel(self.groupBox_6)
        self.label_update_rate.setObjectName(_fromUtf8("label_update_rate"))
        self.gridLayout_14.addWidget(self.label_update_rate, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_14.addWidget(self.label_22, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem1, 5, 0, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_close.setObjectName(_fromUtf8("pushButton_close"))
        self.gridLayout_15.addWidget(self.pushButton_close, 4, 0, 1, 1)
        self.pushButton_proc_control = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_proc_control.setObjectName(_fromUtf8("pushButton_proc_control"))
        self.gridLayout_15.addWidget(self.pushButton_proc_control, 3, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_spectrum = QtWidgets.QMainWindow()
        self.tab_spectrum.setObjectName(_fromUtf8("tab_spectrum"))
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_spectrum)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_spectrum = QtWidgets.QGridLayout()
        self.gridLayout_spectrum.setObjectName(_fromUtf8("gridLayout_spectrum"))
        self.gridLayout_6.addLayout(self.gridLayout_spectrum, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_spectrum, _fromUtf8(""))
        self.tab_symc = QtWidgets.QMainWindow()
        self.tab_symc.setObjectName(_fromUtf8("tab_symc"))
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_symc)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_sync = QtWidgets.QGridLayout()
        self.gridLayout_sync.setObjectName(_fromUtf8("gridLayout_sync"))
        self.gridLayout_5.addLayout(self.gridLayout_sync, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_symc, _fromUtf8(""))
        self.tab_DOA = QtWidgets.QMainWindow()
        self.tab_DOA.setObjectName(_fromUtf8("tab_DOA"))
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_DOA)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_DOA = QtWidgets.QGridLayout()
        self.gridLayout_DOA.setObjectName(_fromUtf8("gridLayout_DOA"))
        self.gridLayout_12.addLayout(self.gridLayout_DOA, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_DOA, _fromUtf8(""))
        self.tab = QtWidgets.QMainWindow()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_23.setMargin(0)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.gridLayout_RD = QtWidgets.QGridLayout()
        self.gridLayout_RD.setObjectName(_fromUtf8("gridLayout_RD"))
        self.gridLayout_23.addLayout(self.gridLayout_RD, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_config.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("KerberosSDR", "KerberosSDR", None))
        self.groupBox_7.setTitle(_translate("KerberosSDR", "Receiver configaration", None))
        self.label_4.setText(_translate("KerberosSDR", "Sampling frequency [MHz]:", None))
        self.comboBox_sampling_freq.setItemText(0, _translate("KerberosSDR", "0.25", None))
        self.comboBox_sampling_freq.setItemText(1, _translate("KerberosSDR", "0.900001", None))
        self.comboBox_sampling_freq.setItemText(2, _translate("KerberosSDR", "1.024", None))
        self.comboBox_sampling_freq.setItemText(3, _translate("KerberosSDR", "1.4", None))
        self.comboBox_sampling_freq.setItemText(4, _translate("KerberosSDR", "1.8", None))
        self.comboBox_sampling_freq.setItemText(5, _translate("KerberosSDR", "1.92", None))
        self.comboBox_sampling_freq.setItemText(6, _translate("KerberosSDR", "2.048", None))
        self.comboBox_sampling_freq.setItemText(7, _translate("KerberosSDR", "2.4", None))
        self.comboBox_sampling_freq.setItemText(8, _translate("KerberosSDR", "2.56", None))
        self.comboBox_sampling_freq.setCurrentIndex(2)

        self.checkBox_en_uniform_gain.setText(_translate("MainWindow", "Uniform Gain", None))


        self.label_3.setText(_translate("KerberosSDR", "Center frequency [MHz]:", None))
        self.label_18.setText(_translate("KerberosSDR", "RX1 Gain [dB]:", None))
        self.comboBox_gain.setItemText(0, _translate("KerberosSDR", "0", None))
        self.comboBox_gain.setItemText(1, _translate("KerberosSDR", "0.9", None))
        self.comboBox_gain.setItemText(2, _translate("KerberosSDR", "1.4", None))
        self.comboBox_gain.setItemText(3, _translate("KerberosSDR", "2.7", None))
        self.comboBox_gain.setItemText(4, _translate("KerberosSDR", "3.7", None))
        self.comboBox_gain.setItemText(5, _translate("KerberosSDR", "7.7", None))
        self.comboBox_gain.setItemText(6, _translate("KerberosSDR", "8.7", None))
        self.comboBox_gain.setItemText(7, _translate("KerberosSDR", "12.5", None))
        self.comboBox_gain.setItemText(8, _translate("KerberosSDR", "14.4", None))
        self.comboBox_gain.setItemText(9, _translate("KerberosSDR", "15.7", None))
        self.comboBox_gain.setItemText(10, _translate("KerberosSDR", "16.6", None))
        self.comboBox_gain.setItemText(11, _translate("KerberosSDR", "19.7", None))
        self.comboBox_gain.setItemText(12, _translate("KerberosSDR", "20.7", None))
        self.comboBox_gain.setItemText(13, _translate("KerberosSDR", "22.9", None))
        self.comboBox_gain.setItemText(14, _translate("KerberosSDR", "25.4", None))
        self.comboBox_gain.setItemText(15, _translate("KerberosSDR", "28.0", None))
        self.comboBox_gain.setItemText(16, _translate("KerberosSDR", "29.7", None))
        self.comboBox_gain.setItemText(17, _translate("KerberosSDR", "32.8", None))
        self.comboBox_gain.setItemText(18, _translate("KerberosSDR", "33.8", None))
        self.comboBox_gain.setItemText(19, _translate("KerberosSDR", "36.4", None))
        self.comboBox_gain.setItemText(20, _translate("KerberosSDR", "37.2", None))
        self.comboBox_gain.setItemText(21, _translate("KerberosSDR", "38.6", None))
        self.comboBox_gain.setItemText(22, _translate("KerberosSDR", "40.2", None))
        self.comboBox_gain.setItemText(23, _translate("KerberosSDR", "42.1", None))
        self.comboBox_gain.setItemText(24, _translate("KerberosSDR", "43.4", None))
        self.comboBox_gain.setItemText(25, _translate("KerberosSDR", "43.9", None))
        self.comboBox_gain.setItemText(26, _translate("KerberosSDR", "44.5", None))
        self.comboBox_gain.setItemText(27, _translate("KerberosSDR", "48.0", None))
        self.comboBox_gain.setItemText(28, _translate("KerberosSDR", "49.6", None))


        self.label_gain_2.setText(_translate("KerberosSDR", "RX2 Gain [dB]:", None))
        self.comboBox_gain_2.setItemText(0, _translate("KerberosSDR", "0", None))
        self.comboBox_gain_2.setItemText(1, _translate("KerberosSDR", "0.9", None))
        self.comboBox_gain_2.setItemText(2, _translate("KerberosSDR", "1.4", None))
        self.comboBox_gain_2.setItemText(3, _translate("KerberosSDR", "2.7", None))
        self.comboBox_gain_2.setItemText(4, _translate("KerberosSDR", "3.7", None))
        self.comboBox_gain_2.setItemText(5, _translate("KerberosSDR", "7.7", None))
        self.comboBox_gain_2.setItemText(6, _translate("KerberosSDR", "8.7", None))
        self.comboBox_gain_2.setItemText(7, _translate("KerberosSDR", "12.5", None))
        self.comboBox_gain_2.setItemText(8, _translate("KerberosSDR", "14.4", None))
        self.comboBox_gain_2.setItemText(9, _translate("KerberosSDR", "15.7", None))
        self.comboBox_gain_2.setItemText(10, _translate("KerberosSDR", "16.6", None))
        self.comboBox_gain_2.setItemText(11, _translate("KerberosSDR", "19.7", None))
        self.comboBox_gain_2.setItemText(12, _translate("KerberosSDR", "20.7", None))
        self.comboBox_gain_2.setItemText(13, _translate("KerberosSDR", "22.9", None))
        self.comboBox_gain_2.setItemText(14, _translate("KerberosSDR", "25.4", None))
        self.comboBox_gain_2.setItemText(15, _translate("KerberosSDR", "28.0", None))
        self.comboBox_gain_2.setItemText(16, _translate("KerberosSDR", "29.7", None))
        self.comboBox_gain_2.setItemText(17, _translate("KerberosSDR", "32.8", None))
        self.comboBox_gain_2.setItemText(18, _translate("KerberosSDR", "33.8", None))
        self.comboBox_gain_2.setItemText(19, _translate("KerberosSDR", "36.4", None))
        self.comboBox_gain_2.setItemText(20, _translate("KerberosSDR", "37.2", None))
        self.comboBox_gain_2.setItemText(21, _translate("KerberosSDR", "38.6", None))
        self.comboBox_gain_2.setItemText(22, _translate("KerberosSDR", "40.2", None))
        self.comboBox_gain_2.setItemText(23, _translate("KerberosSDR", "42.1", None))
        self.comboBox_gain_2.setItemText(24, _translate("KerberosSDR", "43.4", None))
        self.comboBox_gain_2.setItemText(25, _translate("KerberosSDR", "43.9", None))
        self.comboBox_gain_2.setItemText(26, _translate("KerberosSDR", "44.5", None))
        self.comboBox_gain_2.setItemText(27, _translate("KerberosSDR", "48.0", None))
        self.comboBox_gain_2.setItemText(28, _translate("KerberosSDR", "49.6", None))


        self.label_gain_3.setText(_translate("KerberosSDR", "RX3 Gain [dB]:", None))
        self.comboBox_gain_3.setItemText(0, _translate("KerberosSDR", "0", None))
        self.comboBox_gain_3.setItemText(1, _translate("KerberosSDR", "0.9", None))
        self.comboBox_gain_3.setItemText(2, _translate("KerberosSDR", "1.4", None))
        self.comboBox_gain_3.setItemText(3, _translate("KerberosSDR", "2.7", None))
        self.comboBox_gain_3.setItemText(4, _translate("KerberosSDR", "3.7", None))
        self.comboBox_gain_3.setItemText(5, _translate("KerberosSDR", "7.7", None))
        self.comboBox_gain_3.setItemText(6, _translate("KerberosSDR", "8.7", None))
        self.comboBox_gain_3.setItemText(7, _translate("KerberosSDR", "12.5", None))
        self.comboBox_gain_3.setItemText(8, _translate("KerberosSDR", "14.4", None))
        self.comboBox_gain_3.setItemText(9, _translate("KerberosSDR", "15.7", None))
        self.comboBox_gain_3.setItemText(10, _translate("KerberosSDR", "16.6", None))
        self.comboBox_gain_3.setItemText(11, _translate("KerberosSDR", "19.7", None))
        self.comboBox_gain_3.setItemText(12, _translate("KerberosSDR", "20.7", None))
        self.comboBox_gain_3.setItemText(13, _translate("KerberosSDR", "22.9", None))
        self.comboBox_gain_3.setItemText(14, _translate("KerberosSDR", "25.4", None))
        self.comboBox_gain_3.setItemText(15, _translate("KerberosSDR", "28.0", None))
        self.comboBox_gain_3.setItemText(16, _translate("KerberosSDR", "29.7", None))
        self.comboBox_gain_3.setItemText(17, _translate("KerberosSDR", "32.8", None))
        self.comboBox_gain_3.setItemText(18, _translate("KerberosSDR", "33.8", None))
        self.comboBox_gain_3.setItemText(19, _translate("KerberosSDR", "36.4", None))
        self.comboBox_gain_3.setItemText(20, _translate("KerberosSDR", "37.2", None))
        self.comboBox_gain_3.setItemText(21, _translate("KerberosSDR", "38.6", None))
        self.comboBox_gain_3.setItemText(22, _translate("KerberosSDR", "40.2", None))
        self.comboBox_gain_3.setItemText(23, _translate("KerberosSDR", "42.1", None))
        self.comboBox_gain_3.setItemText(24, _translate("KerberosSDR", "43.4", None))
        self.comboBox_gain_3.setItemText(25, _translate("KerberosSDR", "43.9", None))
        self.comboBox_gain_3.setItemText(26, _translate("KerberosSDR", "44.5", None))
        self.comboBox_gain_3.setItemText(27, _translate("KerberosSDR", "48.0", None))
        self.comboBox_gain_3.setItemText(28, _translate("KerberosSDR", "49.6", None))



        self.label_gain_4.setText(_translate("KerberosSDR", "RX4 Gain [dB]:", None))
        self.comboBox_gain_4.setItemText(0, _translate("KerberosSDR", "0", None))
        self.comboBox_gain_4.setItemText(1, _translate("KerberosSDR", "0.9", None))
        self.comboBox_gain_4.setItemText(2, _translate("KerberosSDR", "1.4", None))
        self.comboBox_gain_4.setItemText(3, _translate("KerberosSDR", "2.7", None))
        self.comboBox_gain_4.setItemText(4, _translate("KerberosSDR", "3.7", None))
        self.comboBox_gain_4.setItemText(5, _translate("KerberosSDR", "7.7", None))
        self.comboBox_gain_4.setItemText(6, _translate("KerberosSDR", "8.7", None))
        self.comboBox_gain_4.setItemText(7, _translate("KerberosSDR", "12.5", None))
        self.comboBox_gain_4.setItemText(8, _translate("KerberosSDR", "14.4", None))
        self.comboBox_gain_4.setItemText(9, _translate("KerberosSDR", "15.7", None))
        self.comboBox_gain_4.setItemText(10, _translate("KerberosSDR", "16.6", None))
        self.comboBox_gain_4.setItemText(11, _translate("KerberosSDR", "19.7", None))
        self.comboBox_gain_4.setItemText(12, _translate("KerberosSDR", "20.7", None))
        self.comboBox_gain_4.setItemText(13, _translate("KerberosSDR", "22.9", None))
        self.comboBox_gain_4.setItemText(14, _translate("KerberosSDR", "25.4", None))
        self.comboBox_gain_4.setItemText(15, _translate("KerberosSDR", "28.0", None))
        self.comboBox_gain_4.setItemText(16, _translate("KerberosSDR", "29.7", None))
        self.comboBox_gain_4.setItemText(17, _translate("KerberosSDR", "32.8", None))
        self.comboBox_gain_4.setItemText(18, _translate("KerberosSDR", "33.8", None))
        self.comboBox_gain_4.setItemText(19, _translate("KerberosSDR", "36.4", None))
        self.comboBox_gain_4.setItemText(20, _translate("KerberosSDR", "37.2", None))
        self.comboBox_gain_4.setItemText(21, _translate("KerberosSDR", "38.6", None))
        self.comboBox_gain_4.setItemText(22, _translate("KerberosSDR", "40.2", None))
        self.comboBox_gain_4.setItemText(23, _translate("KerberosSDR", "42.1", None))
        self.comboBox_gain_4.setItemText(24, _translate("KerberosSDR", "43.4", None))
        self.comboBox_gain_4.setItemText(25, _translate("KerberosSDR", "43.9", None))
        self.comboBox_gain_4.setItemText(26, _translate("KerberosSDR", "44.5", None))
        self.comboBox_gain_4.setItemText(27, _translate("KerberosSDR", "48.0", None))
        self.comboBox_gain_4.setItemText(28, _translate("KerberosSDR", "49.6", None))








        self.pushButton_set_receiver_config.setText(_translate("KerberosSDR", "Set", None))
        self.groupBox_8.setTitle(_translate("KerberosSDR", "IQ preprocessing", None))
        self.label_19.setText(_translate("KerberosSDR", "FIR tap size:", None))
        self.label_2.setText(_translate("KerberosSDR", "Filter BW [kHz]: ", None))
        self.label.setText(_translate("KerberosSDR", "DC compensation:", None))
        self.label_20.setText(_translate("KerberosSDR", "Decimation:", None))
        self.spinBox_fir_tap_size.setToolTip(_translate("KerberosSDR", "<html><head/><body><p>Set to 0 to disable FIR filtering.</p></body></html>", None))
        self.checkBox_en_spectrum.setText(_translate("KerberosSDR", "Enable spectrum display", None))
        self.groupBox.setTitle(_translate("KerberosSDR", "Syncronization", None))
        self.label_12.setText(_translate("KerberosSDR", "Enable sync display:", None))
        self.label_32.setText(_translate("KerberosSDR", "Noise source ON/OFF", None))
        self.spinBox_resync_time.setToolTip(_translate("KerberosSDR", "<html><head/><body><p>Set to 10 or higher to automatically resync samples every x seconds. Values below 10 disable timed resync.</p></body></html>", None))
        self.label_resync_time.setText(_translate("KerberosSDR", "Set Resync Time", None))
        self.pushButton_del_sync_history.setText(_translate("KerberosSDR", "Delete history", None))
        self.pushButton_sync.setText(_translate("KerberosSDR", "Sample sync", None))
        self.pushButton_iq_calib.setText(_translate("KerberosSDR", "Calibrate IQ", None))
        self.groupBox_2.setTitle(_translate("KerberosSDR", "Antenna configarion", None))
        self.label_21.setText(_translate("KerberosSDR", "Arrangement:", None))
        #self.label_24.setText(_translate("KerberosSDR", "Spacing [lambda]:", None))
        self.label_24.setText(_translate("KerberosSDR", "Spacing [meters]:", None))
        self.comboBox_antenna_alignment.setToolTip(_translate("KerberosSDR", "<html><head/><body><p>ULA (Uniform Linear Array)<br/>UCA (Uniform Ciruclar Array)</p></body></html>", None))
        self.comboBox_antenna_alignment.setItemText(0, _translate("KerberosSDR", "ULA", None))
        self.comboBox_antenna_alignment.setItemText(1, _translate("KerberosSDR", "UCA", None))
        self.pushButton_DOA_cal_90.setText(_translate("KerberosSDR", "Calibrate 90 deg", None))
        self.pushButton_DOA_cal_90.setToolTip(_translate("KerberosSDR", "<html><head/><body><p>NOTE: Reserved for future use. Not fully implemented in this version.</p></body></html>", None))

        self.groupBox_4.setTitle(_translate("KerberosSDR", "DOA estimation", None))
        self.label_10.setText(_translate("KerberosSDR", "Sample size 2^x:", None))
        self.spinBox_DOA_sample_size.setToolTip(_translate("KerberosSDR", "<html><head/><body><p>NOTE: Reserved for future use. Does nothing in this version.</p></body></html>", None))
        self.spinBox_pr_sample_size.setToolTip(_translate("KerberosSDR", "<html><head/><body><p>NOTE: Reserved for future use. Does nothing in this version.</p></body></html>", None))

        self.label_11.setText(_translate("KerberosSDR", "Enable/Disable:", None))
        self.label_9.setText(_translate("KerberosSDR", "MUSIC", None))
        self.label_8.setText(_translate("KerberosSDR", "MEM", None))
        self.label_7.setText(_translate("KerberosSDR", "Capon", None))
        self.label_6.setText(_translate("KerberosSDR", "Bartlett", None))
        self.label_16.setText(_translate("KerberosSDR", "FB average:", None))
        self.label_5.setText(_translate("KerberosSDR", "Methods:", None))
        self.label_15.setText(_translate("KerberosSDR", "Corr. matrix", None))
        self.checkBox_en_passive_radar.setText(_translate("KerberosSDR", "Enable passive radar processing", None))
        self.groupBox_3.setTitle(_translate("KerberosSDR", "Channel configuration", None))
        self.label_13.setText(_translate("KerberosSDR", "Reference channel:", None))
        self.label_14.setText(_translate("KerberosSDR", "Surveillance channel:", None))
        self.label_30.setText(_translate("KerberosSDR", "Sample size 2^x:", None))
        self.groupBox_5.setTitle(_translate("KerberosSDR", "Time domain clutter cancellation", None))
        self.label_23.setText(_translate("KerberosSDR", "Enable/Disable:", None))
        self.label_25.setText(_translate("KerberosSDR", "Method:", None))
        self.label_26.setText(_translate("KerberosSDR", "Filter dimension:", None))
        self.comboBox_td_filter_method.setItemText(0, _translate("KerberosSDR", "Wiener - SSMI", None))
        self.groupBox_9.setTitle(_translate("KerberosSDR", "Cross-Correlation Detector", None))
        self.label_27.setText(_translate("KerberosSDR", "max Range:", None))
        self.label_28.setText(_translate("KerberosSDR", "max Doppler:", None))
        self.label_29.setText(_translate("KerberosSDR", "Windowing:", None))
        self.comboBox_cc_det_windowing.setItemText(0, _translate("KerberosSDR", "Rectangular", None))
        self.comboBox_cc_det_windowing.setItemText(1, _translate("KerberosSDR", "Hamming", None))
        self.label_31.setText(_translate("KerberosSDR", "Dynamic range: ", None))

        self.groupBox_11.setTitle(_translate("MainWindow", "Peak Hold", None))
        self.label_37.setText(_translate("MainWindow", "Peak Hold: ", None))


        self.groupBox_10.setTitle(_translate("MainWindow", "Automatic detection (CA-CFAR)", None))
        self.label_35.setToolTip(_translate("MainWindow", "<html><head/><body><p>Estimation window has a rectangular shape ( L x L cell), where L is the input data here</p></body></html>", None))
        self.label_35.setText(_translate("MainWindow", "Estimation window: ", None))
        self.label_34.setText(_translate("MainWindow", "Threshold [dB]:", None))
        self.label_33.setText(_translate("MainWindow", "Enable/Disable", None))
        self.label_36.setToolTip(_translate("MainWindow", "<html><head/><body><p>Guard window has a rectangular shape ( G x GL cell), where G is the input data here</p></body></html>", None))
        self.label_36.setText(_translate("MainWindow", "Guard window: ", None))

        self.groupBox_6.setTitle(_translate("KerberosSDR", "Status ", None))
        self.label_power_level.setText(_translate("KerberosSDR", "OK", None))
        self.label_17.setText(_translate("KerberosSDR", "Powel level:", None))
        self.label_update_rate.setText(_translate("KerberosSDR", "-ms", None))
        self.label_22.setText(_translate("KerberosSDR", "Update rate:", None))
        self.pushButton_close.setText(_translate("KerberosSDR", "Exit", None))
        self.pushButton_proc_control.setText(_translate("KerberosSDR", "Start processing", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_spectrum), _translate("KerberosSDR", "Configuration and Spectrum", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_symc), _translate("KerberosSDR", "Sync", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DOA), _translate("KerberosSDR", "DOA estimation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("KerberosSDR", "Passive radar", None))
